plugins = []
functionsDirectory = "C:\\Users\\tania\\New_frontend\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
headers = []

[dev]
functions = "netlify/functions"

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\tania\\New_frontend\\public"
publishOrigin = "config"
commandOrigin = "ui"
command = "npm run build"
functions = "C:\\Users\\tania\\New_frontend\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]